#!/bin/sh
  #
  # Gradle start up script for POSIX generated by "Gradle" build system.
  #
  APP_NAME="Gradle"
  APP_BASE_NAME=`basename "$0"`
  APP_HOME=`pwd -P`
  MAX_FD="maximum"
  warn () { echo "$*"; }
  die () { echo; echo "$*"; echo; exit 1; }
  OS_NAME=`uname`
  case $OS_NAME in
    Darwin*) os_type=Darwin;;
    Linux*) os_type=Linux;;
    CYGWIN*) os_type=Cygwin;;
    MINGW*) os_type=MinGw;;
    *) os_type=Unknown;;
  esac
  CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar
  JAVA_EXE=java
  if [ -n "$JAVA_HOME" ]; then JAVA_EXE="$JAVA_HOME/bin/java"; fi
  exec "$JAVA_EXE" -classpath "$CLASSPATH" org.gradle.wrapper.GradleWrapperMain "$@"
  